### ISSUE TITLE
增量编译问题

### ISSUE THREAD

**Issue by Quyunshuo** [rain9155/PluginDemo#2]
开启了增量编译后，方法耗时监测会有很多方法没打印，关闭后就正常了
感觉总有一些异常情况，比如我关闭增量编译之前，一直打印kotlin的协程调度器的方法耗时，gradle里配置的time也不生效

**Comment by rain9155** [comment]
异常情况是在开启增量编译之后才出现的吗

**Comment by Quyunshuo** [comment]
时间有些久远，有点记不清楚了，印象中是开启增量后出的问题，而且现在好像是Kotlin所有带返回值的方法（或者是不带返回值的）会丢失插入的打印耗时的后半分代码，导致不会打印耗时

**Comment by rain9155** [comment]
感谢指出问题，已经修复了，原因是耗时检测插件中没有对带有返回值的方法进行插桩，详情可看[30b129](https://github.com/rain9155/PluginDemo/commit/30b129e6e82dcbc5af8e344a3abf997e859b64d7#diff-d4e277f1cc57213a7a8f13962ca8ddbdc7c1a2672678954d29608940d4a711f4)提交
